services:
  - type: web
    name: iventia-arte-capital
    runtime: docker
    dockerfilePath: ../Dockerfile.arte-capital
    dockerContext: ../..
    buildArgs:
      - key: VITE_API_URL
        value: https://iventia-api.onrender.com/api/v1/arte-capital
    envVars:
      - key: PORT
        value: 3003
      - key: NODE_ENV
        value: production
