services:
  - type: web
    name: iventia-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
